### ISSUE TITLE
Using total_count_limit raises an exception

### ISSUE THREAD

**Issue by jgallinari** [duffelhq/paginator#164]
Hello,
I found a little bug concerning the `total_count_limit` parameter.

This is what I have in my query params:

```elixir
params: %{include_total_count: true, limit: 10, total_count_limit: "20"}
```
And this is what I get when running the query:

```elixir
[error] #PID<0.802.0> running OssWeb.Endpoint (connection #PID<0.801.0>, stream id 1) terminated
Server: localhost:4013 (http)
Request: GET /v1/oem/test/subscriber?limit=10&include_total_count=true&total_count_limit=20
** (exit) an exception was raised:
    ** (ArithmeticError) bad argument in arithmetic expression
        (paginator 1.1.0) lib/paginator.ex:371: Paginator.total_count/4
        (paginator 1.1.0) lib/paginator.ex:181: Paginator.paginate/4
```

Looks like lib/paginator.ex:371, which is
```elixir
      |> limit(^(total_count_limit + 1))
```
should be replaced with:
```elixir
      |> limit(^total_count_limit + 1)
```

What do you think?

Regards,
Jerome

**Comment by jgallinari** [comment]
Sorry, my mistake. I was using the wrong type for the parameter.
